using System.Collections.Generic;
using System.IO;
using System.Text;
using Evo.Infrastructure.Services.PlatformInfo.Config;
using UnityEditor;

namespace Evo.Infrastructure.Editor.EvoTools.Build
{
    public static class EvoBuildMenuGenerator
    {
        private const string LegacyGeneratedFilePath = "Assets/_Project/Generated/EvoTools/BuildMenu/EvoGeneratedBuildMenu.cs";
        private const string GeneratedFolder = "Assets/_Project/Generated/Editor/EvoTools/BuildMenu";
        private const string GeneratedFilePath = GeneratedFolder + "/EvoGeneratedBuildMenu.cs";

        public static string Generate(BuildGlobalConfig globalConfig, PlatformCatalog platformCatalog)
        {
            DeleteLegacyGeneratedMenu();
            EnsureFolder(GeneratedFolder);
            var text = BuildSource(globalConfig, platformCatalog);
            File.WriteAllText(GeneratedFilePath, text, Encoding.UTF8);
            AssetDatabase.ImportAsset(GeneratedFilePath);
            AssetDatabase.Refresh();
            return GeneratedFilePath;
        }

        private static void DeleteLegacyGeneratedMenu()
        {
            if (AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(LegacyGeneratedFilePath) != null)
            {
                AssetDatabase.DeleteAsset(LegacyGeneratedFilePath);
                return;
            }

            if (File.Exists(LegacyGeneratedFilePath))
            {
                File.Delete(LegacyGeneratedFilePath);
            }

            var metaPath = LegacyGeneratedFilePath + ".meta";
            if (File.Exists(metaPath))
            {
                File.Delete(metaPath);
            }
        }

        private static string BuildSource(BuildGlobalConfig globalConfig, PlatformCatalog platformCatalog)
        {
            var globalGuid = GetGuid(globalConfig);
            var catalogGuid = GetGuid(platformCatalog);
            var profiles = CollectProfiles(globalConfig);
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("// Generated by EvoTools/Build. Do not edit manually.");
            builder.AppendLine("using Evo.Infrastructure.Editor.EvoTools.Build;");
            builder.AppendLine("using UnityEditor;");
            builder.AppendLine();
            builder.AppendLine("namespace Game.Editor.Generated.EvoTools.Build");
            builder.AppendLine("{");
            builder.AppendLine("    internal static class EvoGeneratedBuildMenu");
            builder.AppendLine("    {");

            for (var i = 0; i < profiles.Count; i++)
            {
                AppendProfileMethods(builder, profiles[i], globalGuid, catalogGuid, i);
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static List<PlatformBuildProfile> CollectProfiles(BuildGlobalConfig globalConfig)
        {
            var result = new List<PlatformBuildProfile>();
            if (globalConfig?.Profiles == null)
            {
                return result;
            }

            for (var i = 0; i < globalConfig.Profiles.Count; i++)
            {
                var profile = globalConfig.Profiles[i];
                if (profile != null && profile.ShowInGeneratedMenu)
                {
                    result.Add(profile);
                }
            }

            return result;
        }

        private static void AppendProfileMethods(
            StringBuilder builder,
            PlatformBuildProfile profile,
            string globalGuid,
            string catalogGuid,
            int index)
        {
            var profileGuid = GetGuid(profile);
            var menuName = EscapeStringLiteral(SanitizeMenuName(profile.DisplayName));
            var methodSuffix = $"{SanitizeMethodSuffix(profile.ProfileId)}_{index}";

            builder.AppendLine($"        [MenuItem(\"EvoTools/Build/Apply/{menuName}\", false, {1000 + index})]");
            builder.AppendLine($"        private static void Apply_{methodSuffix}()");
            builder.AppendLine("        {");
            builder.AppendLine($"            EvoBuildMenuActions.ApplyProfile(\"{globalGuid}\", \"{profileGuid}\", \"{catalogGuid}\");");
            builder.AppendLine("        }");
            builder.AppendLine();

            builder.AppendLine($"        [MenuItem(\"EvoTools/Build/Validate/{menuName}\", false, {1100 + index})]");
            builder.AppendLine($"        private static void Validate_{methodSuffix}()");
            builder.AppendLine("        {");
            builder.AppendLine($"            EvoBuildMenuActions.ValidateProfile(\"{globalGuid}\", \"{profileGuid}\");");
            builder.AppendLine("        }");
            builder.AppendLine();

            builder.AppendLine($"        [MenuItem(\"EvoTools/Build/Build/{menuName}\", false, {1200 + index})]");
            builder.AppendLine($"        private static void Build_{methodSuffix}()");
            builder.AppendLine("        {");
            builder.AppendLine($"            EvoBuildMenuActions.BuildProfile(\"{globalGuid}\", \"{profileGuid}\", \"{catalogGuid}\", false);");
            builder.AppendLine("        }");
            builder.AppendLine();

            builder.AppendLine($"        [MenuItem(\"EvoTools/Build/Build And Run/{menuName}\", false, {1300 + index})]");
            builder.AppendLine($"        private static void BuildAndRun_{methodSuffix}()");
            builder.AppendLine("        {");
            builder.AppendLine($"            EvoBuildMenuActions.BuildProfile(\"{globalGuid}\", \"{profileGuid}\", \"{catalogGuid}\", true);");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        private static string GetGuid(UnityEngine.Object asset)
        {
            if (asset == null)
            {
                return string.Empty;
            }

            var path = AssetDatabase.GetAssetPath(asset);
            return string.IsNullOrWhiteSpace(path) ? string.Empty : AssetDatabase.AssetPathToGUID(path);
        }

        private static void EnsureFolder(string folder)
        {
            var normalized = folder.Replace('\\', '/').Trim('/');
            var parts = normalized.Split('/');
            var current = parts[0];
            for (var i = 1; i < parts.Length; i++)
            {
                var next = $"{current}/{parts[i]}";
                if (!AssetDatabase.IsValidFolder(next))
                {
                    AssetDatabase.CreateFolder(current, parts[i]);
                }

                current = next;
            }
        }

        private static string SanitizeMenuName(string value)
        {
            return string.IsNullOrWhiteSpace(value) ? "Unnamed Profile" : value.Replace("/", "-").Trim();
        }

        private static string SanitizeMethodSuffix(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return "Profile";
            }

            var chars = value.Trim().ToCharArray();
            for (var i = 0; i < chars.Length; i++)
            {
                if (!char.IsLetterOrDigit(chars[i]))
                {
                    chars[i] = '_';
                }
            }

            var result = new string(chars);
            if (!char.IsLetter(result[0]) && result[0] != '_')
            {
                result = "_" + result;
            }

            return result;
        }

        private static string EscapeStringLiteral(string value)
        {
            return (value ?? string.Empty)
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n")
                .Replace("\t", "\\t");
        }
    }
}
