// <auto-generated>
// This file is generated by AnalyticsEventCatalog.
// Do not edit this file manually. Use the catalog asset and regenerate.
// </auto-generated>
namespace _Project.Scripts.Infrastructure.Services.Analytics
{
    [System.CodeDom.Compiler.GeneratedCode("AnalyticsEventCatalog", "1.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public static class AnalyticsEventKeys
    {
        // Event Keys
        public const string EVENT_AD_SHOW_RESULT = "ad_show_result";
        public const string EVENT_INTER_START = "Inter_Start";
        public const string EVENT_INTER_SUCCESS = "Inter_Success";
        public const string EVENT_INTER_FAIL = "Inter_Fail";
        public const string EVENT_BATTLE_START = "BattleStart";
        public const string EVENT_BATTLE_WIN = "BattleWin";
        public const string EVENT_BATTLE_LOSE = "BattleLose";
        public const string EVENT_BATTLE_SCENE_OPEN_1 = "BattleSceneOpen_1";
        public const string EVENT_BATTLE_SCENE_OPEN_2 = "BattleSceneOpen_2";
        public const string EVENT_BATTLE_SCENE_OPEN_3 = "BattleSceneOpen_3";
        public const string EVENT_BATTLE_USER_ACTIVE_1 = "BattleUserActive_1";
        public const string EVENT_BATTLE_USER_ACTIVE_2 = "BattleUserActive_2";
        public const string EVENT_BATTLE_USER_ACTIVE_3 = "BattleUserActive_3";
        public const string EVENT_CLOSE_GAME = "CloseGame";
        public const string EVENT_FIRST_SESSION = "FirstSession";
        public const string EVENT_PLAY_AGAIN = "PlayAgain";
        public const string EVENT_PLAYER_KILL = "PlayerKill";
        public const string EVENT_AD_IMPRESSION = "ad_impression";
        public const string EVENT_AD_REWARD = "ad_reward";
        public const string EVENT_APP_CLEAR_DATA = "app_clear_data";
        public const string EVENT_APP_EXCEPTION = "app_exception";
        public const string EVENT_APP_REMOVE = "app_remove";
        public const string EVENT_APP_UPDATE = "app_update";
        public const string EVENT_FIRST_OPEN = "first_open";
        public const string EVENT_OS_UPDATE = "os_update";
        public const string EVENT_SCREEN_VIEW = "screen_view";
        public const string EVENT_SESSION_START = "session_start";
        public const string EVENT_USER_ENGAGEMENT = "user_engagement";

        // Parameter Keys
        public const string PARAM_STATUS = "status";
        public const string PARAM_AD_TYPE = "ad_type";
        public const string PARAM_ADAPTER_ID = "adapter_id";
        public const string PARAM_FALLBACK_USED = "fallback_used";
        public const string PARAM_DURATION_MS = "duration_ms";
        public const string PARAM_ERROR = "error";
        public const string PARAM_CURRENCY = "currency";
        public const string PARAM_REVENUE = "revenue";
        public const string PARAM_TRANSACTION_ID = "transaction_id";
        public const string PARAM_ITEM_ID = "item_id";
        public const string PARAM_PURCHASE_TOKEN = "purchase_token";
        public const string PARAM_RECEIPT = "receipt";
        public const string PARAM_AD_PLATFORM = "ad_platform";
        public const string PARAM_NETWORK = "network";
        public const string PARAM_UNIT_ID = "unit_id";
        public const string PARAM_FORMAT = "format";
        public const string PARAM_PLACEMENT = "placement";
        public const string PARAM_NETWORK_PLACEMENT = "network_placement";
        public const string PARAM_COUNTRY_CODE = "country";
        public const string PARAM_KILLS = "kills";
        public const string PARAM_ROUND_NUM = "round_num";
        public const string PARAM_RESULT = "result";
        public const string PARAM_SCREEN = "screen";
    }
}
