// <auto-generated>
// This file is generated by LeaderboardKeyCatalog.
// Do not edit this file manually. Use the catalog asset and regenerate.
// </auto-generated>
namespace _Project.Scripts.Infrastructure.Services.Leaderboard
{
    [System.CodeDom.Compiler.GeneratedCode("LeaderboardKeyCatalog", "1.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public static class LeaderboardKeys
    {
        // Leaderboard Keys

        // Parameter Keys

    }
}
