using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using _Project.Scripts.Infrastructure.Services.Config;
#if ODIN_INSPECTOR
using Sirenix.OdinInspector;
#endif
using UnityEngine;

#if UNITY_EDITOR
using UnityEditor;
using EvoDebug = _Project.Scripts.Infrastructure.Services.Debug.EvoDebug;
#endif

namespace _Project.Scripts.Infrastructure.Services.Analytics.Config
{
    public enum AnalyticsKeyKind
    {
        Event = 0,
        Parameter = 1
    }

    [Serializable]
    public sealed class AnalyticsKeyEntry
    {
        public AnalyticsKeyKind Kind = AnalyticsKeyKind.Event;
        public string Name;
        public string Key;
#if ODIN_INSPECTOR
        [LabelText("Tooltip Key")]
#endif
        [Tooltip("@_Project.Scripts.Editor.EvoTools.EvoToolsLocalization.Get(\"analytics.catalog.tooltip_key\", \"Localization key in EvoTools table for tooltip. Leave empty to use Comment.\")")]
        public string TooltipKey;
        [TextArea] public string Comment;
    }

    [CreateAssetMenu(fileName = "AnalyticsEventCatalog", menuName = "Project/Analytics/Event Catalog")]
    [GameConfig("Analytics")]
    public sealed class AnalyticsEventCatalog : ScriptableObject, IGameConfig
    {
#if ODIN_INSPECTOR
        [InfoBox("@_Project.Scripts.Editor.EvoTools.EvoToolsLocalization.Get(\"analytics.catalog.info\", \"Add tooltip text for keys in EvoTools localization table. Use Tooltip Key to reference it.\")", InfoMessageType.Info)]
        [ListDrawerSettings(ShowFoldout = true, DefaultExpandedState = false, ShowIndexLabels = true, ListElementLabelName = "Key")]
#endif
        [SerializeField] private List<AnalyticsKeyEntry> entries = new();

        public IReadOnlyList<AnalyticsKeyEntry> Entries => entries;

#if UNITY_EDITOR
#if ODIN_INSPECTOR
        [Button(ButtonSizes.Medium, Name = "Generate Analytics Keys")]
#endif
        private void GenerateAnalyticsKeys()
        {
            var path = "Assets/_Project/Scripts/Infrastructure/Services/Analytics/AnalyticsEventKeys.cs";
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// This file is generated by AnalyticsEventCatalog.");
            builder.AppendLine("// Do not edit this file manually. Use the catalog asset and regenerate.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine("namespace _Project.Scripts.Infrastructure.Services.Analytics");
            builder.AppendLine("{");
            builder.AppendLine("    [System.CodeDom.Compiler.GeneratedCode(\"AnalyticsEventCatalog\", \"1.0\")]");
            builder.AppendLine("    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");
            builder.AppendLine("    public static class AnalyticsEventKeys");
            builder.AppendLine("    {");

            AppendGroup(builder, AnalyticsKeyKind.Event, "Event Keys");
            AppendGroup(builder, AnalyticsKeyKind.Parameter, "Parameter Keys");

            builder.AppendLine("    }");
            builder.AppendLine("}");

            File.WriteAllText(path, builder.ToString());
            AssetDatabase.ImportAsset(path);
        }

#if ODIN_INSPECTOR
        [Button(ButtonSizes.Medium, Name = "Import Analytics Keys")]
#endif
        private void ImportAnalyticsKeys()
        {
            var path = "Assets/_Project/Scripts/Infrastructure/Services/Analytics/AnalyticsEventKeys.cs";
            if (!File.Exists(path))
            {
                EvoDebug.LogWarning("AnalyticsEventCatalog: AnalyticsEventKeys.cs not found.", nameof(AnalyticsEventCatalog));
                return;
            }

            var lines = File.ReadAllLines(path);
            var imported = new List<AnalyticsKeyEntry>();
            var currentKind = AnalyticsKeyKind.Event;

            for (var i = 0; i < lines.Length; i++)
            {
                var line = lines[i].Trim();
                if (line.StartsWith("// Event Keys", StringComparison.Ordinal))
                {
                    currentKind = AnalyticsKeyKind.Event;
                    continue;
                }

                if (line.StartsWith("// Parameter Keys", StringComparison.Ordinal))
                {
                    currentKind = AnalyticsKeyKind.Parameter;
                    continue;
                }

                if (!line.StartsWith("public const string ", StringComparison.Ordinal))
                {
                    continue;
                }

                var parsed = TryParseConst(line, out var name, out var key);
                if (!parsed)
                {
                    continue;
                }

                imported.Add(new AnalyticsKeyEntry
                {
                    Kind = currentKind,
                    Name = name,
                    Key = key
                });
            }

            if (imported.Count == 0)
            {
                EvoDebug.LogWarning("AnalyticsEventCatalog: no constants found to import.", nameof(AnalyticsEventCatalog));
                return;
            }

            entries = imported;
            EditorUtility.SetDirty(this);
            AssetDatabase.SaveAssets();
        }

        private void AppendGroup(StringBuilder builder, AnalyticsKeyKind kind, string header)
        {
            builder.AppendLine($"        // {header}");

            var nameSet = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var keySet = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            for (var i = 0; i < entries.Count; i++)
            {
                var entry = entries[i];
                if (entry == null || entry.Kind != kind)
                {
                    continue;
                }

                var name = SanitizeConstName(entry.Name);
                var key = entry.Key ?? string.Empty;

                if (string.IsNullOrWhiteSpace(name) || string.IsNullOrWhiteSpace(key))
                {
                    EvoDebug.LogWarning($"AnalyticsEventCatalog: skipping empty entry at index {i}.", nameof(AnalyticsEventCatalog));
                    continue;
                }

                if (!nameSet.Add(name))
                {
                    EvoDebug.LogWarning($"AnalyticsEventCatalog: duplicate const name '{name}'.", nameof(AnalyticsEventCatalog));
                    continue;
                }

                if (!keySet.Add(key))
                {
                    EvoDebug.LogWarning($"AnalyticsEventCatalog: duplicate key '{key}'.", nameof(AnalyticsEventCatalog));
                }

                if (!string.IsNullOrWhiteSpace(entry.Comment))
                {
                    builder.AppendLine($"        // {entry.Comment}");
                }

                builder.AppendLine($"        public const string {name} = \"{key}\";");
            }

            builder.AppendLine();
        }

        private static bool TryParseConst(string line, out string name, out string key)
        {
            name = null;
            key = null;

            var nameStart = line.IndexOf("public const string ", StringComparison.Ordinal);
            if (nameStart < 0)
            {
                return false;
            }

            nameStart += "public const string ".Length;
            var nameEnd = line.IndexOf(' ', nameStart);
            if (nameEnd < 0)
            {
                return false;
            }

            name = line.Substring(nameStart, nameEnd - nameStart).Trim();
            var equalsIndex = line.IndexOf('=', nameEnd);
            if (equalsIndex < 0)
            {
                return false;
            }

            var quoteStart = line.IndexOf('"', equalsIndex);
            if (quoteStart < 0)
            {
                return false;
            }

            var quoteEnd = line.IndexOf('"', quoteStart + 1);
            if (quoteEnd < 0)
            {
                return false;
            }

            key = line.Substring(quoteStart + 1, quoteEnd - quoteStart - 1);
            return !string.IsNullOrWhiteSpace(name) && !string.IsNullOrWhiteSpace(key);
        }

        private static string SanitizeConstName(string rawName)
        {
            if (string.IsNullOrWhiteSpace(rawName))
            {
                return string.Empty;
            }

            var builder = new StringBuilder(rawName.Length);
            for (var i = 0; i < rawName.Length; i++)
            {
                var c = rawName[i];
                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    builder.Append(char.ToUpperInvariant(c));
                }
            }

            if (builder.Length == 0)
            {
                return string.Empty;
            }

            if (char.IsDigit(builder[0]))
            {
                builder.Insert(0, "KEY_");
            }

            return builder.ToString();
        }
#endif
    }
}
